/*

 BACK_M.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\gbmb\boxing.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backMapWidth 20
#define backMapHeight 18
#define backMapBank 0

extern unsigned char backMap[];

/* End of BACK_M.H */
