/*

 BACK_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define backTilesBank 0

/* Super Gameboy palette 0 */
#define backTilesSGBPal0c0 6108
#define backTilesSGBPal0c1 8935
#define backTilesSGBPal0c2 6596
#define backTilesSGBPal0c3 6368

/* Super Gameboy palette 1 */
#define backTilesSGBPal1c0 6108
#define backTilesSGBPal1c1 8935
#define backTilesSGBPal1c2 6596
#define backTilesSGBPal1c3 6368

/* Super Gameboy palette 2 */
#define backTilesSGBPal2c0 6108
#define backTilesSGBPal2c1 8935
#define backTilesSGBPal2c2 6596
#define backTilesSGBPal2c3 6368

/* Super Gameboy palette 3 */
#define backTilesSGBPal3c0 6108
#define backTilesSGBPal3c1 8935
#define backTilesSGBPal3c2 6596
#define backTilesSGBPal3c3 6368

/* Gameboy Color palette 0 */
#define backTilesCGBPal0c0 0
#define backTilesCGBPal0c1 3775
#define backTilesCGBPal0c2 811
#define backTilesCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define backTilesCGBPal1c0 32767
#define backTilesCGBPal1c1 3775
#define backTilesCGBPal1c2 811
#define backTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define backTilesCGBPal2c0 6108
#define backTilesCGBPal2c1 8935
#define backTilesCGBPal2c2 6596
#define backTilesCGBPal2c3 6368

/* Gameboy Color palette 3 */
#define backTilesCGBPal3c0 6108
#define backTilesCGBPal3c1 8935
#define backTilesCGBPal3c2 6596
#define backTilesCGBPal3c3 6368

/* Gameboy Color palette 4 */
#define backTilesCGBPal4c0 6108
#define backTilesCGBPal4c1 8935
#define backTilesCGBPal4c2 6596
#define backTilesCGBPal4c3 6368

/* Gameboy Color palette 5 */
#define backTilesCGBPal5c0 6108
#define backTilesCGBPal5c1 8935
#define backTilesCGBPal5c2 6596
#define backTilesCGBPal5c3 6368

/* Gameboy Color palette 6 */
#define backTilesCGBPal6c0 6108
#define backTilesCGBPal6c1 8935
#define backTilesCGBPal6c2 6596
#define backTilesCGBPal6c3 6368

/* Gameboy Color palette 7 */
#define backTilesCGBPal7c0 6108
#define backTilesCGBPal7c1 8935
#define backTilesCGBPal7c2 6596
#define backTilesCGBPal7c3 6368
/* CGBpalette entries. */
extern unsigned char backTilesCGB[];
/* Start of tile array. */
extern unsigned char backTiles[];

/* End of BACK_T.H */
